### ISSUE TITLE
support for daylight saving time (DST)

### ISSUE THREAD

**Issue by arosenhagen** [kbwood/countdown#64]
currently the plugin doesn't take DST into account.

**Comment by kmentch** [comment]
Would also like to see this fixed.

**Comment by afattahi54** [comment]
+1 hope this would be fixed

**Comment by afattahi54** [comment]
I used a workaround mentioned in `http://stackoverflow.com/questions/11887934/check-if-daylight-saving-time-is-in-effect-and-if-it-is-for-how-many-hours` but hope that the component could handle it internally

**Comment by animgr** [comment]
We really appreciate your effort to fix this as well. 
Regards

**Comment by lilibit1985** [comment]
I have the same problem. I am looking forward to the fix.😊

**Comment by parisa314** [comment]
Unfortunately i have the same problem as well.would  you please help us with fixing this issue.
I really appreciate you in advance.

**Comment by kbwood** [comment]
JavaScript doesn't handle dates well and wouldn't reliably compute whether daylight saving is in effect, especially from year-to-year and from timezone-to-timezone. There's nothing stopping you adding this code into your own pages if you want to use it.

**Comment by afattahi54** [comment]
I have made some tests the code which i have sent you worked fine.
Any way is it possible that I set 'since' date and the counter did not change its value. As i have mentioed in my question the counter changes the date i pass it. This means that the counter work with the hour and minute as normal number instead of date.
Thanks again for this greate add on 😁

**Comment by kbwood** [comment]
When you use the relative time format for the value of _since_, the plugin applies that to the current date/time. In the case of it covering the change of daylight saving, it looks like the hours are subtracted normally to give a time before DST, but then the difference to the current time is one hour less due to the lost hour during that period. As I said, JavaScript doesn't deal with date/times well. You could specify a UTC date/time to sidestep these issues, see _$.countdown.UTCDate_.

**Comment by afattahi54** [comment]
Thanks i have see the code and read the description of UTCDate well i tested but i think i am not using it correctly 
I have correct hour and minute from server and try to make a new UTCDate from it 

So if correct hour is 14 and minute is 43 i set 'since' as

'since:$.countdown.UTCDate(2016,3,23,14,43,0)'

**Comment by kbwood** [comment]
The first parameter must be the timezone for your date/time, either in minutes or hours from GMT. See the documentation.

**Comment by afattahi54** [comment]
I confused 😞 so the client time zone is still used so the finall computed date is dependent on client time zone

Well let me ask this way .... I want the client shows server clock which is totaly independent of client clock, client time zone or whethere the client has sets its DST or not ... As you may have guessed I just want the counter initiates itself by the hour and minute which i pass to it and the plugin just keep count it upward ... In this way i have clock with is totaly independent of client clock 

Actually its a banking application and i want user sees the correct server time on pages his client may have incorrect clock ... Well not just see clock but a working clock !!

**Comment by LCallaghan84** [comment]
What about using the moment timezone js plugin with the countdown

Here is the link
http://momentjs.com/timezone/ 

I am sure its possible to make those two work together

**Comment by kbwood** [comment]
Yes, you could use moment.js to perform your date/time calculations and then convert that to the corresponding JS Date (toDate()) for use with Countdown.

**Comment by LCallaghan84** [comment]
how would I convert that? is there a example you can provide me with or some kind of documentation/guide?

**Comment by kbwood** [comment]
There's the MomentJS documentation at http://momentjs.com/docs/ and http://momentjs.com/timezone/docs/.

It looks like your code would be something like this:

var target = moment.tz("2014-06-01 12:00", "America/New_York").toDate();
$('#myCountdown').countdown({until: target});
